---- 갤러리 상세보기 뷰 ver1 ----
CREATE OR REPLACE VIEW GALLERYFORDETAIL
AS 
SELECT G.BID, GID, BTITLE, BCONTENT, M.MPROFILE, M.MNAME,  GC.GCATEGORY, C.CCLNAME, GTAG, bcount, BDATE
FROM GALLERY G
JOIN BOARD B ON (G.BID=B.BID)
JOIN MEMBER M ON (B.BWRITER = M.MID)
JOIN GCATEGORY GC ON (G.GCATEGORY = GC.GCATEGORY_ID)
JOIN CCL C ON (G.CCLID = C.CCLID)
ORDER BY G.GID
WITH READ ONLY;
