-- 20181113 수정

---------------- 테스트 데이터 삽입 ----------------
-- 1. 회원
-- INSERT INTO MEMBER VALUES(시퀀스, 프로필, 이메일, 비밀번호, 닉네임, 가입날짜, 호두, 회원상태)
INSERT INTO MEMBER VALUES(
SEQ_MID.NEXTVAL, NULL, 'admin', '1234', '관리자', DEFAULT, DEFAULT, DEFAULT);

INSERT INTO MEMBER VALUES(
SEQ_MID.NEXTVAL, NULL, 'sjk1992@nate.com', 'test01', 'TDteam', DEFAULT, DEFAULT, DEFAULT);

INSERT INTO MEMBER VALUES(
SEQ_MID.NEXTVAL, NULL, 'TEST01@nate.com', 'PASS01', 'TEST01', DEFAULT, DEFAULT, DEFAULT);

INSERT INTO MEMBER VALUES(
SEQ_MID.NEXTVAL, NULL, 'TEST02@nate.com', 'PASS02', 'TEST02', DEFAULT, DEFAULT, DEFAULT);

INSERT INTO MEMBER VALUES(
SEQ_MID.NEXTVAL, NULL, 'TEST03@nate.com', 'PASS03', 'TEST03', DEFAULT, DEFAULT, DEFAULT);

INSERT INTO MEMBER VALUES(
SEQ_MID.NEXTVAL, NULL, 'TEST04@nate.com', 'PASS04', 'TEST04', DEFAULT, DEFAULT, DEFAULT);

SELECT * FROM MEMBER;

-- 2. 게시판
--INSERT INTO BOARD VALUES(시퀀스, 게시판타입, 제목, 내용, 조회수, 작성일, 글상태, 신고횟수, 작성자);
INSERT INTO BOARD VALUES(
SEQ_BID.NEXTVAL, 1, '공지사항 제목입니다.', '내용입니다.', DEFAULT, DEFAULT, DEFAULT, DEFAULT, 1);
INSERT INTO BOARD VALUES(
SEQ_BID.NEXTVAL, 1, '공지사항 제목입니다.', '내용입니다.', DEFAULT, DEFAULT, DEFAULT, DEFAULT, 1);
INSERT INTO BOARD VALUES(
SEQ_BID.NEXTVAL, 2, '갤러리 제목입니다.', '내용입니다.', DEFAULT, DEFAULT, DEFAULT, DEFAULT, 2);
INSERT INTO BOARD VALUES(
SEQ_BID.NEXTVAL, 2, '갤러리 제목입니다.', '내용입니다.', DEFAULT, DEFAULT, DEFAULT, DEFAULT, 2);
INSERT INTO BOARD VALUES(
SEQ_BID.NEXTVAL, 2, '갤러리 제목입니다.', '내용입니다.', DEFAULT, DEFAULT, DEFAULT, DEFAULT, 3);
INSERT INTO BOARD VALUES(
SEQ_BID.NEXTVAL, 2, '갤러리 제목입니다.', '내용입니다.', DEFAULT, DEFAULT, DEFAULT, DEFAULT, 3);
INSERT INTO BOARD VALUES(
SEQ_BID.NEXTVAL, 2, '갤러리 제목입니다.', '내용입니다.', DEFAULT, DEFAULT, DEFAULT, DEFAULT, 4);
INSERT INTO BOARD VALUES(
SEQ_BID.NEXTVAL, 2, '갤러리 제목입니다.', '내용입니다.', DEFAULT, DEFAULT, DEFAULT, DEFAULT, 4);
INSERT INTO BOARD VALUES(
SEQ_BID.NEXTVAL, 3, '프로젝트 제목입니다.', '내용입니다.', DEFAULT, DEFAULT, DEFAULT, DEFAULT, 2);
INSERT INTO BOARD VALUES(
SEQ_BID.NEXTVAL, 3, '프로젝트 제목입니다.', '내용입니다.', DEFAULT, DEFAULT, DEFAULT, DEFAULT, 3);
INSERT INTO BOARD VALUES(
SEQ_BID.NEXTVAL, 3, '프로젝트 제목입니다.', '내용입니다.', DEFAULT, DEFAULT, DEFAULT, DEFAULT, 4);

SELECT * FROM BOARD;

-- 3. 갤러리 
-- INSERT INTO GALLERY VALUES(시퀀스, 카테고리, 태그, 좋아요수, BOARD글번호, CCL)
INSERT INTO GALLERY VALUES(
SEQ_GID.NEXTVAL, 1, '태그1, 태그2, 태그3', DEFAULT, 3, 1);
INSERT INTO GALLERY VALUES(
SEQ_GID.NEXTVAL, 2, '태그2, 태그3, 태그4', DEFAULT, 4, 2);
INSERT INTO GALLERY VALUES(
SEQ_GID.NEXTVAL, 3, '태그3, 태그4, 태그5', DEFAULT, 5, 3);
INSERT INTO GALLERY VALUES(
SEQ_GID.NEXTVAL, 4, '태그, 태그5, 태그6', DEFAULT, 6, 4);
INSERT INTO GALLERY VALUES(
SEQ_GID.NEXTVAL, 1, '태그5, 태그6, 태그7', DEFAULT, 7, 5);
INSERT INTO GALLERY VALUES(
SEQ_GID.NEXTVAL, 2, '태그6, 태그7, 태그8', DEFAULT, 8, 6);

SELECT * FROM GALLERY;

-- 4. 프로젝트
-- INSERT INTO PROJECT VALUES(시퀀스, 종료일, BOARD글번호, 태그)
INSERT INTO PROJECT VALUES(SEQ_JID.NEXTVAL, SYSDATE, 9, '태그1, 태그2, 태그3');
INSERT INTO PROJECT VALUES(SEQ_JID.NEXTVAL, SYSDATE, 10, NULL);
INSERT INTO PROJECT VALUES(SEQ_JID.NEXTVAL, SYSDATE, 11, NULL);

SELECT * FROM PROJECT;

-- 5. 첨부파일


-- 6. 댓글
-- INSERT INTO BOARDCOMMENT VALUES(시퀀스, 내용, 작성일, 상태, BOARD글번호, 작성자, 신고횟수, REF)
INSERT INTO BOARDCOMMENT VALUES(SEQ_CID.NEXTVAL, '댓글 내용입니다1', DEFAULT, DEFAULT, 3, 2, DEFAULT, NULL);
INSERT INTO BOARDCOMMENT VALUES(SEQ_CID.NEXTVAL, '댓글 내용입니다2', DEFAULT, DEFAULT, 3, 3, DEFAULT, NULL);
INSERT INTO BOARDCOMMENT VALUES(SEQ_CID.NEXTVAL, '댓글 내용입니다3', DEFAULT, DEFAULT, 3, 4, DEFAULT, NULL);
INSERT INTO BOARDCOMMENT VALUES(SEQ_CID.NEXTVAL, '댓글 내용입니다4', DEFAULT, DEFAULT, 10, 2, DEFAULT, NULL);
INSERT INTO BOARDCOMMENT VALUES(SEQ_CID.NEXTVAL, '댓글 내용입니다5', DEFAULT, DEFAULT, 10, 3, DEFAULT, NULL);
INSERT INTO BOARDCOMMENT VALUES(SEQ_CID.NEXTVAL, '댓글 내용입니다1', DEFAULT, DEFAULT, 5, 2, DEFAULT, NULL);
INSERT INTO BOARDCOMMENT VALUES(SEQ_CID.NEXTVAL, '댓글 내용입니다2', DEFAULT, DEFAULT, 5, 2, DEFAULT, 4);
INSERT INTO BOARDCOMMENT VALUES(SEQ_CID.NEXTVAL, '댓글 내용입니다3', DEFAULT, DEFAULT, 5, 2, DEFAULT, 5);
INSERT INTO BOARDCOMMENT VALUES(SEQ_CID.NEXTVAL, '댓글 내용입니다4', DEFAULT, DEFAULT, 5, 2, DEFAULT, 2);
INSERT INTO BOARDCOMMENT VALUES(SEQ_CID.NEXTVAL, '댓글 내용입니다5', DEFAULT, DEFAULT, 5, 2, DEFAULT, 3);
INSERT INTO BOARDCOMMENT VALUES(SEQ_CID.NEXTVAL, '댓글 내용입니다6', DEFAULT, DEFAULT, 5, 2, DEFAULT, NULL);
INSERT INTO BOARDCOMMENT VALUES(SEQ_CID.NEXTVAL, '댓글 내용입니다7', DEFAULT, 'N', 5, 2, DEFAULT, NULL);
INSERT INTO BOARDCOMMENT VALUES(SEQ_CID.NEXTVAL, '댓글 내용입니다8', DEFAULT, 'N', 5, 2, DEFAULT, NULL);

SELECT * FROM BOARDCOMMENT;

-- 7. 결제
-- INSERT INTO PAYMENT VALUES(시퀀스, 결제정보, 결제일, 회원번호)
INSERT INTO PAYMENT VALUES(SEQ_PID.NEXTVAL, 1, DEFAULT, 2);
INSERT INTO PAYMENT VALUES(SEQ_PID.NEXTVAL, 2, DEFAULT, 2);
INSERT INTO PAYMENT VALUES(SEQ_PID.NEXTVAL, 1, DEFAULT, 2);
INSERT INTO PAYMENT VALUES(SEQ_PID.NEXTVAL, 3, DEFAULT, 2);
INSERT INTO PAYMENT VALUES(SEQ_PID.NEXTVAL, 2, DEFAULT, 2);
INSERT INTO PAYMENT VALUES(SEQ_PID.NEXTVAL, 3, DEFAULT, 4);
INSERT INTO PAYMENT VALUES(SEQ_PID.NEXTVAL, 2, DEFAULT, 4);
INSERT INTO PAYMENT VALUES(SEQ_PID.NEXTVAL, 4, DEFAULT, 4);
INSERT INTO PAYMENT VALUES(SEQ_PID.NEXTVAL, 1, DEFAULT, 4);
INSERT INTO PAYMENT VALUES(SEQ_PID.NEXTVAL, 1, DEFAULT, 3);

SELECT * FROM PAYMENT;

-- 8. 후원
INSERT INTO SPON VALUES(SEQ_SID.NEXTVAL, 2, DEFAULT, 2, 1);
INSERT INTO SPON VALUES(SEQ_SID.NEXTVAL, 2, DEFAULT, 2, 3);
INSERT INTO SPON VALUES(SEQ_SID.NEXTVAL, 2, DEFAULT, 3, 4);
INSERT INTO SPON VALUES(SEQ_SID.NEXTVAL, 2, DEFAULT, 3, 5);

-- 9. 신고
-- INSERT INTO REPORT VALUES(시퀀스, 신고사유번호, 기타사유, 신고일, 신고한회원, 댓글번호, BOARD글번호)
INSERT INTO REPORT VALUES(SEQ_RID.NEXTVAL, 5, '기타사유1', SYSDATE, 1, 1, 3);
INSERT INTO REPORT VALUES(SEQ_RID.NEXTVAL, 2, NULL, SYSDATE, 1, 1, 3);
INSERT INTO REPORT VALUES(SEQ_RID.NEXTVAL, 1, NULL, SYSDATE, 1, 3, 3);
INSERT INTO REPORT VALUES(SEQ_RID.NEXTVAL, 4, NULL, SYSDATE, 1, 5, 10);
INSERT INTO REPORT VALUES(SEQ_RID.NEXTVAL, 3, NULL, SYSDATE, 1, 4, 10);
INSERT INTO REPORT VALUES(SEQ_RID.NEXTVAL, 1, NULL, SYSDATE, 1, NULL, 5);
INSERT INTO REPORT VALUES(SEQ_RID.NEXTVAL, 4, NULL, SYSDATE, 1, NULL, 6);
INSERT INTO REPORT VALUES(SEQ_RID.NEXTVAL, 3, NULL, SYSDATE, 1, NULL, 10);

-- 10. 팔로우
-- INSERT INTO FOLLOW VALUES(시퀀스, 팔로워(팬=로그인한회원), 팔로우)
INSERT INTO FOLLOW VALUES(SEQ_FID.NEXTVAL, 2, 3);
INSERT INTO FOLLOW VALUES(SEQ_FID.NEXTVAL, 2, 4);
INSERT INTO FOLLOW VALUES(SEQ_FID.NEXTVAL, 3, 4);
INSERT INTO FOLLOW VALUES(SEQ_FID.NEXTVAL, 4, 2);
INSERT INTO FOLLOW VALUES(SEQ_FID.NEXTVAL, 4, 3);
INSERT INTO FOLLOW VALUES(SEQ_FID.NEXTVAL, 4, 5);
INSERT INTO FOLLOW VALUES(SEQ_FID.NEXTVAL, 5, 2);
INSERT INTO FOLLOW VALUES(SEQ_FID.NEXTVAL, 5, 3);
INSERT INTO FOLLOW VALUES(SEQ_FID.NEXTVAL, 5, 4);

SELECT * FROM FOLLOW;

-- 11. 좋아요
-- INSERT INTO LIKEIT VALUES(시퀀스, 회원번호, BOARD글번호);
INSERT INTO LIKEIT VALUES(SEQ_LID.NEXTVAL, 2, 3);
INSERT INTO LIKEIT VALUES(SEQ_LID.NEXTVAL, 3, 3);
INSERT INTO LIKEIT VALUES(SEQ_LID.NEXTVAL, 4, 3);
INSERT INTO LIKEIT VALUES(SEQ_LID.NEXTVAL, 5, 3);
INSERT INTO LIKEIT VALUES(SEQ_LID.NEXTVAL, 2, 4);
INSERT INTO LIKEIT VALUES(SEQ_LID.NEXTVAL, 3, 4);
INSERT INTO LIKEIT VALUES(SEQ_LID.NEXTVAL, 2, 10);
INSERT INTO LIKEIT VALUES(SEQ_LID.NEXTVAL, 3, 10);
INSERT INTO LIKEIT VALUES(SEQ_LID.NEXTVAL, 4, 10);
INSERT INTO LIKEIT VALUES(SEQ_LID.NEXTVAL, 5, 11);

SELECT * FROM LIKEIT;

-- 12. 알람
INSERT INTO ALARM VALUES(SEQ_AID.NEXTVAL, 3, '가입을 축하합니다.', DEFAULT, DEFAULT);

COMMIT;





